### ISSUE TITLE
Shiny - 1950/1982 comparisons not working

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/seagrass-analysis#11]
For the shiny app (https://shiny.tbep.org/seagrass-analysis/), on the mgmt area tabs, the comparisons aren't occurring for 1950 or 1982 (just NAs for %change)

**Comment by fawda123** [comment]
@Gmangrove yea that's an issue of not having the 1950 and 1982 source layers available to get the estimates for the management areas.  @esherwoo77 tells me there are not reliable sources for these data.  I know we have these layers somewhere but not the original ones used to get the "official" baseline estimates.  In the interim, I'd need to have an informative message popup saying these aren't available, otherwise it looks like a bug.
